name: uluslararasialevivakfi
description: "Uluslararası Alevi Vakfı mobil uygulaması"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Sürümleri en güncel ve stabil hallerine çektik
  webview_flutter: ^4.9.0
  shared_preferences: ^2.3.5 # Crash riskine karşı güncel tutuyoruz
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Proje SDK'nıza daha uygun sürüm

flutter:
  uses-material-design: true

  # Assets hizalaması çok önemlidir, boşluklara dikkat!
  assets:
    - assets/
    - assets/app_logo.png