name: uluslararasialevivakfi
description: "Uluslararası Alevi Vakfı mobil uygulaması"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Gerekli paketler (bunlar olmadan hata alırsın)
  webview_flutter: ^4.9.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Logo ve diğer resimler için assets klasörü
  assets:
    - assets/
    - assets/app_logo.png   # varsa logo buraya gelecekt